export const VERSION = '0.1.0'
export { cx } from './utils/cx'
export { ThemeProvider, useTheme } from './theme/ThemeProvider'
export type { Theme, ThemeProviderProps } from './theme/ThemeProvider'
export { Icon } from './components/Icon/Icon'
export type { IconProps } from './components/Icon/Icon'
export { Button } from './components/Button/Button'
export type { ButtonProps, ButtonVariant, ButtonSize } from './components/Button/Button'

// Phase 2 — Tier 1 components
export { IconButton } from './components/IconButton/IconButton'
export type { IconButtonProps, IconButtonVariant, IconButtonSize } from './components/IconButton/IconButton'
export { TextField } from './components/TextField/TextField'
export type { TextFieldProps, TextFieldSize } from './components/TextField/TextField'
export { Select } from './components/Select/Select'
export type { SelectProps, SelectOption, SelectOptionGroup, SelectItems, SelectSize } from './components/Select/Select'
export { Checkbox } from './components/Checkbox/Checkbox'
export type { CheckboxProps } from './components/Checkbox/Checkbox'
export { Radio } from './components/Radio/Radio'
export type { RadioProps } from './components/Radio/Radio'
export { RadioGroup } from './components/Radio/RadioGroup'
export type { RadioGroupProps, RadioOrientation } from './components/Radio/RadioGroup'
export { Switch } from './components/Switch/Switch'
export type { SwitchProps, SwitchLabelPlacement } from './components/Switch/Switch'
export { Chip } from './components/Chip/Chip'
export type { ChipProps, StatusChipProps, FilterChipProps, ChipStatus, ChipSize } from './components/Chip/Chip'
export { Badge } from './components/Chip/Badge'
export type { BadgeProps, BadgeTone } from './components/Chip/Badge'
export { Card, CardHeader, CardBody, CardFooter } from './components/Card/Card'
export type { CardProps, CardSectionProps, CardSurface, CardElevation } from './components/Card/Card'
export { Dialog } from './components/Dialog/Dialog'
export type { DialogProps, DialogSize } from './components/Dialog/Dialog'
export { Tooltip } from './components/Tooltip/Tooltip'
export type { TooltipProps, TooltipPlacement } from './components/Tooltip/Tooltip'
export { Tabs } from './components/Tabs/Tabs'
export type { TabsProps, TabItem, TabsSize } from './components/Tabs/Tabs'

// Phase 3 — Tier 2 components
export { Table } from './components/Table/Table'
export type { TableProps, Column, ColumnAlign, SortState, SortDirection, TableDensity } from './components/Table/Table'
export { StatCard } from './components/StatCard/StatCard'
export type { StatCardProps, StatCardStatus, StatCardDelta, DeltaDirection } from './components/StatCard/StatCard'
export { Progress } from './components/Progress/Progress'
export type { ProgressProps, ProgressSize, ProgressTone, ThresholdStop } from './components/Progress/Progress'
export { Gauge } from './components/Progress/Gauge'
export type { GaugeProps, GaugeSize } from './components/Progress/Gauge'
export { AlertBanner } from './components/AlertBanner/AlertBanner'
export type { AlertBannerProps, AlertVariant } from './components/AlertBanner/AlertBanner'
export { ToastProvider, useToast } from './components/Toast/Toast'
export type { ToastProviderProps, ToastVariant, ToastOptions, ToastInstance, ToastPosition, ToastApi, ToastAction } from './components/Toast/Toast'
export { Sidebar, SidebarItem, SidebarSection, Topbar } from './components/Navigation/Navigation'
export type { SidebarProps, SidebarItemProps, SidebarSectionProps, TopbarProps } from './components/Navigation/Navigation'
export { Breadcrumb } from './components/Breadcrumb/Breadcrumb'
export type { BreadcrumbProps, BreadcrumbItem } from './components/Breadcrumb/Breadcrumb'
export { EmptyState } from './components/EmptyState/EmptyState'
export type { EmptyStateProps, EmptyStateSize } from './components/EmptyState/EmptyState'
export { Skeleton, SkeletonText } from './components/Skeleton/Skeleton'
export type { SkeletonProps, SkeletonVariant, SkeletonTextProps } from './components/Skeleton/Skeleton'
export { SearchInput } from './components/SearchInput/SearchInput'
export type { SearchInputProps, SearchInputSize } from './components/SearchInput/SearchInput'
export { Stepper } from './components/Stepper/Stepper'
export type { StepperProps, StepperItem, StepStatus, StepperOrientation, StepperSize } from './components/Stepper/Stepper'

// Phase 4 — Tier 3 (composition + visualization)
export { AppShell, useAppShell } from './components/AppShell/AppShell'
export type { AppShellProps } from './components/AppShell/AppShell'
export { Chart } from './components/Chart/Chart'
export { LineChart } from './components/Chart/LineChart'
export { BarChart } from './components/Chart/BarChart'
export { PieChart } from './components/Chart/PieChart'
export type { ChartProps, ChartType, ChartPoint, ChartSeries, ChartBaseProps, ReferenceLine, ReferenceLineTone } from './components/Chart/Chart'
export type { LineChartProps } from './components/Chart/LineChart'
export type { BarChartProps } from './components/Chart/BarChart'
export type { PieChartProps } from './components/Chart/PieChart'
export { PageHeader } from './components/PageHeader/PageHeader'
export type { PageHeaderProps, PageHeaderSize, HeadingLevel } from './components/PageHeader/PageHeader'
